#include "Team_ProjectA/SOS/public/SOS_Hide_baby.h"
#include "Components/SkeletalMeshComponent.h"
#include "NiagaraFunctionLibrary.h"
#include "Components/SceneComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Team_ProjectA/SOS/public/SOS_Hide_SphereComp.h"
#include "UObject/ConstructorHelpers.h"

// Sets default values
ASOS_Hide_baby::ASOS_Hide_baby()
{
	PrimaryActorTick.bCanEverTick = true;

	// ë£¨íŠ¸ ì»´í¬ë„ŒíŠ¸ ì„¤ì •
	Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
	RootComponent = Root;

	// Skeletal Mesh ì»´í¬ë„ŒíŠ¸ ìƒì„± ë° ë£¨íŠ¸ì— ë¶€ì°©
	Mesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("Mesh"));
	Mesh->SetupAttachment(Root);

	// ë©”ì‹œ ë¡œë“œ
	static ConstructorHelpers::FObjectFinder<USkeletalMesh> MeshAsset(TEXT("/Game/00_Project/00_Asset/Enemy/Hideoplast/Meshes/SK_Hideoplast.SK_Hideoplast"));
	if (MeshAsset.Succeeded())
	{
		Mesh->SetSkeletalMesh(MeshAsset.Object);
	}

	// ë©”ì‹œ í¬ê¸° ì¡°ì •
	Mesh->SetRelativeScale3D(Hide_Baby_Scale);
	
	
	// ì¶©ëŒ ì´ˆê¸°í™”
	Mesh->SetCollisionProfileName(TEXT("Projectile"));

	// ë©”ì‹œ ê¸°ë³¸ íšŒì „
	Mesh->SetRelativeRotation(Hide_Baby_Rotate);

	// Collision ì»´í¬ë„ŒíŠ¸ ìƒì„±
	BabyCollision = CreateDefaultSubobject<USOS_Hide_SphereComp>(TEXT("BabyCollision"));
	BabyCollision->SetupAttachment(Mesh);  // Meshì— ë¶€ì°©
	
	// Overlap ì´ë²¤íŠ¸ ì„¤ì •
	BabyCollision->OnComponentBeginOverlap.AddDynamic(this, &ASOS_Hide_baby::OnOverlapBegin);
}

// Called when the game starts or when spawned
void ASOS_Hide_baby::BeginPlay()
{
	Super::BeginPlay();

	// ì´ˆê¸° ì†ë„ ì„¤ì • (Forward Vector ê¸°ì¤€)
	Velocity = GetActorForwardVector() * Speed;
}

// Called every frame
void ASOS_Hide_baby::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// í¬ë¬¼ì„  ìš´ë™ ì²˜ë¦¬
	Velocity += Gravity * DeltaTime;
	FVector NewLocation = GetActorLocation() + Velocity * DeltaTime;
	SetActorLocation(NewLocation);
}

void ASOS_Hide_baby::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
	UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	/*
	if (!OtherActor || OtherActor == this)
	{
		return;
	}
	*/
	
	// ë‚˜ì´ì•„ê°€ë¼ íš¨ê³¼ ì¬ìƒ
	if (NiagaraEffect)
	{
		UNiagaraFunctionLibrary::SpawnSystemAtLocation(
			GetWorld(),
			NiagaraEffect,
			GetActorLocation(),
			FRotator::ZeroRotator
		);
		UE_LOG(LogTemp, Warning, TEXT("Niagara effect played at %s"), *GetActorLocation().ToString());
	}

	// ğŸ”¹ ëœë¤ ì‚¬ìš´ë“œ ì¬ìƒ
	if (ImpactSounds.Num() > 0)  // ë°°ì—´ì´ ë¹„ì–´ìˆì§€ ì•Šì€ì§€ í™•ì¸
	{
		int32 RandomIndex = FMath::RandRange(0, ImpactSounds.Num() - 1); // ëœë¤ ì¸ë±ìŠ¤ ì„ íƒ
		USoundBase* RandomSound = ImpactSounds[RandomIndex];

		if (RandomSound)
		{
			UGameplayStatics::PlaySoundAtLocation(this, RandomSound, GetActorLocation());
			UE_LOG(LogTemp, Warning, TEXT("Impact sound played: %s"), *RandomSound->GetName());
		}
	}

	
	
	// ë°ë¯¸ì§€ ì²˜ë¦¬
	UGameplayStatics::ApplyDamage(OtherActor, Baby_Damage, GetInstigatorController(), this, nullptr);
	UE_LOG(LogTemp, Warning, TEXT("Applied %f damage to %s"), Baby_Damage, *OtherActor->GetName());
	
	// íˆ¬ì‚¬ì²´ ì‚­ì œ
	Destroy();
}
