// Fill out your copyright notice in the Description page of Project Settings.


#include "Team_ProjectA/SOS/public/SOS_Hide_SphereComp.h"

#include "JHS_C_Player.h"
#include "Components/SkeletalMeshComponent.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "Team_ProjectA/SOS/public/SOS_BOSS_Character.h"

// ìƒì„±ìž
USOS_Hide_SphereComp::USOS_Hide_SphereComp()
{
	// ê¸°ë³¸ ì¶©ëŒ ì„¤ì •
	InitSphereRadius(30.0f);  // êµ¬ì²´ì˜ ë°˜ê²½ ì„¤ì • (í•„ìš”ì— ë”°ë¼ ë³€ê²½ ê°€ëŠ¥)
	//SetCollisionProfileName(TEXT("OverlapAllDynamic"));  // ê¸°ë³¸ ì¶©ëŒ í”„ë¡œíŒŒì¼ ì„¤ì •

	// Overlap ì´ë²¤íŠ¸ í™œì„±í™”
	OnComponentBeginOverlap.AddDynamic(this, &USOS_Hide_SphereComp::OnOverlapBegin);

	// ì´ˆê¸°ì—ëŠ” ì¶©ëŒ ë¹„í™œì„±í™” (í•„ìš” ì‹œ í™œì„±í™”)
	UPrimitiveComponent::SetCollisionEnabled(ECollisionEnabled::NoCollision);
}

// ë³¸(Bone)ì— ë¶€ì°©
void USOS_Hide_SphereComp::AttachToBone(USkeletalMeshComponent* Mesh, FName BoneName)
{
	if (Mesh)
	{
		// ë³¸ì— ì»´í¬ë„ŒíŠ¸ ë¶€ì°©
		// SnapToTargetIncludingScale ê·œì¹™ì„ ì‚¬ìš©í•˜ì—¬ ë³¸ì˜ ìœ„ì¹˜, íšŒì „, ìŠ¤ì¼€ì¼ì— ì •í™•ížˆ ë§žì¶¥ë‹ˆë‹¤.
		AttachToComponent(Mesh, FAttachmentTransformRules::SnapToTargetIncludingScale, BoneName);

		UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_SphereComp: Attached to Bone: %s"), *BoneName.ToString());
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("USOS_Hide_SphereComp: Mesh is null, cannot attach."));
	}
}

// ì¶©ëŒ í™œì„±í™”
void USOS_Hide_SphereComp::EnableCollision()
{
	SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);  // ì¶©ëŒ í™œì„±í™”
	//UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_SphereComp: Collision Enabled"));
}

// ì¶©ëŒ ë¹„í™œì„±í™”
void USOS_Hide_SphereComp::DisableCollision()
{
	SetCollisionEnabled(ECollisionEnabled::NoCollision);  // ì¶©ëŒ ë¹„í™œì„±í™”
	//UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_SphereComp: Collision Disabled"));
}

// Overlap ì´ë²¤íŠ¸ ì²˜ë¦¬ (ë‹¤ë¥¸ ì•¡í„°ì™€ ì¶©ëŒí–ˆì„ ë•Œ í˜¸ì¶œ)
void USOS_Hide_SphereComp::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
	UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (OtherActor && OtherActor != GetOwner())
	{
		// AJHS_C_Player í´ëž˜ìŠ¤ì˜ ì•¡í„°ì¸ì§€ í™•ì¸
		if (OtherActor->IsA(AJHS_C_Player::StaticClass()))
		{
			UE_LOG(LogTemp, Log, TEXT("USOS_Hide_Box_Comp: Applied %f damage to %s"), SphereDamage, *OtherActor->GetName());
			
			// ë°ë¯¸ì§€ ì ìš©
			UGameplayStatics::ApplyDamage(
				OtherActor,          // í”¼í•´ë¥¼ ë°›ëŠ” ì•¡í„°
				SphereDamage,         // ë°ë¯¸ì§€ ê°’ (ë©¤ë²„ ë³€ìˆ˜ë¡œ ì„¤ì •)
				GetOwner()->GetInstigatorController(), // ë°ë¯¸ì§€ë¥¼ ì¤€ ì»¨íŠ¸ë¡¤ëŸ¬
				GetOwner(),          // ë°ë¯¸ì§€ë¥¼ ì¤€ ì•¡í„°
				UDamageType::StaticClass() // ë°ë¯¸ì§€ íƒ€ìž…
			);

			
			
			// ðŸ”¹ ëžœë¤ ì‚¬ìš´ë“œ ìž¬ìƒ
			if (ImpactSounds.Num() > 0)  // ë°°ì—´ì´ ë¹„ì–´ìžˆì§€ ì•Šì€ì§€ í™•ì¸
			{
				int32 RandomIndex = FMath::RandRange(0, ImpactSounds.Num() - 1); // ëžœë¤ ì¸ë±ìŠ¤ ì„ íƒ
				USoundBase* RandomSound = ImpactSounds[RandomIndex];

				if (RandomSound)
				{
					UGameplayStatics::PlaySoundAtLocation(this, RandomSound, GetOwner()->GetActorLocation());
					UE_LOG(LogTemp, Warning, TEXT("Impact sound played: %s"), *RandomSound->GetName());
				}
			}
			
			DisableCollision();

			// ë¡œê·¸ ì¶œë ¥
		}
		else
		{
			// ì˜ˆì™¸ ì²˜ë¦¬: í”Œë ˆì´ì–´ê°€ ì•„ë‹Œ ì•¡í„°ì— ëŒ€í•´ ë¡œê·¸ ì¶œë ¥
			//UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_Box_Comp: Skipped damage for non-player actor %s"), *OtherActor->GetName());
		}
	}

	
}
