// Fill out your copyright notice in the Description page of Project Settings.


#include "Team_ProjectA/SOS/public/SOS_Hide_Box_Comp.h"

#include "JHS_C_Player.h"
#include "Kismet/GameplayStatics.h"

USOS_Hide_Box_Comp::USOS_Hide_Box_Comp()
{
	// BoxComponentì˜ í¬ê¸°ë¥¼ ë§¤ê°œë³€ìˆ˜ë¡œ ì„¤ì •
	InitBoxExtent(FVector(50.0f, 50.0f, 50.0f));

	
	// Overlap ì´ë²¤íŠ¸ í™œì„±í™”
	OnComponentBeginOverlap.AddDynamic(this, &USOS_Hide_Box_Comp::OnOverlapBegin);

	// ì´ˆê¸°ì—ëŠ” ì¶©ëŒ ë¹„í™œì„±í™” (í•„ìš” ì‹œ í™œì„±í™”)
	UPrimitiveComponent::SetCollisionEnabled(ECollisionEnabled::NoCollision);

	
}

void USOS_Hide_Box_Comp::AttachToBone(USkeletalMeshComponent* Mesh, FName BoneName)
{
	if (Mesh)
	{
		// ë³¸ì— ì»´í¬ë„ŒíŠ¸ ë¶€ì°©
		// SnapToTargetIncludingScale ê·œì¹™ì„ ì‚¬ìš©í•˜ì—¬ ë³¸ì˜ ìœ„ì¹˜, íšŒì „, ìŠ¤ì¼€ì¼ì— ì •í™•ížˆ ë§žì¶¥ë‹ˆë‹¤.
		AttachToComponent(Mesh, FAttachmentTransformRules::SnapToTargetIncludingScale, BoneName);

		UE_LOG(LogTemp, Warning, TEXT("SOS_Hide_Box_Comp: Attached to Bone: %s"), *BoneName.ToString());
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("SOS_Hide_Box_Comp: Mesh is null, cannot attach."));
	}
}

void USOS_Hide_Box_Comp::EnableCollision()
{
	SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);  // ì¶©ëŒ í™œì„±í™”
	UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_SphereComp: Collision Enabled"));
}

void USOS_Hide_Box_Comp::DisableCollision()
{
	SetCollisionEnabled(ECollisionEnabled::NoCollision);  // ì¶©ëŒ ë¹„í™œì„±í™”
	UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_SphereComp: Collision Disabled"));
}

void USOS_Hide_Box_Comp::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
	UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (OtherActor && OtherActor != GetOwner())
	{
		// AJHS_C_Player í´ëž˜ìŠ¤ì˜ ì•¡í„°ì¸ì§€ í™•ì¸
		if (OtherActor->IsA(AJHS_C_Player::StaticClass()))
		{
			// ë°ë¯¸ì§€ ì ìš©
			UGameplayStatics::ApplyDamage(
				OtherActor,          // í”¼í•´ë¥¼ ë°›ëŠ” ì•¡í„°
				BoxDamage,         // ë°ë¯¸ì§€ ê°’ (ë©¤ë²„ ë³€ìˆ˜ë¡œ ì„¤ì •)
				GetOwner()->GetInstigatorController(), // ë°ë¯¸ì§€ë¥¼ ì¤€ ì»¨íŠ¸ë¡¤ëŸ¬
				GetOwner(),          // ë°ë¯¸ì§€ë¥¼ ì¤€ ì•¡í„°
				UDamageType::StaticClass() // ë°ë¯¸ì§€ íƒ€ìž…
			);

			// ðŸ”¹ ëžœë¤ ì‚¬ìš´ë“œ ìž¬ìƒ
			if (ImpactSounds.Num() > 0)  // ë°°ì—´ì´ ë¹„ì–´ìžˆì§€ ì•Šì€ì§€ í™•ì¸
			{
				int32 RandomIndex = FMath::RandRange(0, ImpactSounds.Num() - 1); // ëžœë¤ ì¸ë±ìŠ¤ ì„ íƒ
				USoundBase* RandomSound = ImpactSounds[RandomIndex];

				if (RandomSound)
				{
					UGameplayStatics::PlaySoundAtLocation(this, RandomSound, GetOwner()->GetActorLocation());
					UE_LOG(LogTemp, Warning, TEXT("Impact sound played: %s"), *RandomSound->GetName());
				}
			}

			DisableCollision();
			
			// ë¡œê·¸ ì¶œë ¥
			UE_LOG(LogTemp, Log, TEXT("USOS_Hide_Box_Comp: Applied %f damage to %s"), BoxDamage, *OtherActor->GetName());
		}
		else
		{
			// ì˜ˆì™¸ ì²˜ë¦¬: í”Œë ˆì´ì–´ê°€ ì•„ë‹Œ ì•¡í„°ì— ëŒ€í•´ ë¡œê·¸ ì¶œë ¥
			//UE_LOG(LogTemp, Warning, TEXT("USOS_Hide_Box_Comp: Skipped damage for non-player actor %s"), *OtherActor->GetName());
		}
	}

	
}
