#include "Team_ProjectA/SOS/public/SOS_NiagaraActor.h"
#include "Kismet/GameplayStatics.h"
#include "NiagaraFunctionLibrary.h"
#include "Components/BoxComponent.h"

// Sets default values
ASOS_NiagaraActor::ASOS_NiagaraActor()
{
	PrimaryActorTick.bCanEverTick = true;

	// Root Component ìƒì„±
	RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));

	// Box Collision ìƒì„±
	BoxCollision = CreateDefaultSubobject<UBoxComponent>(TEXT("BoxCollision"));
	BoxCollision->SetupAttachment(RootComponent);
	BoxCollision->SetCollisionEnabled(ECollisionEnabled::NoCollision); // ì´ˆê¸°ì— ë¹„í™œì„±í™”
	BoxCollision->SetGenerateOverlapEvents(true);
	BoxCollision->SetCollisionObjectType(ECC_Pawn);
	BoxCollision->SetCollisionResponseToAllChannels(ECR_Ignore);
	BoxCollision->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
	BoxCollision->OnComponentBeginOverlap.AddDynamic(this, &ASOS_NiagaraActor::OnBoxComponentBeginOverlap);

	// Niagara Component ìƒì„±
	NiagaraComponent = CreateDefaultSubobject<UNiagaraComponent>(TEXT("NiagaraComponent"));
	NiagaraComponent->SetupAttachment(RootComponent);
	NiagaraComponent->OnSystemFinished.AddDynamic(this, &ASOS_NiagaraActor::OnNiagaraSystemFinished);
}

// Called when the game starts or when spawned
void ASOS_NiagaraActor::BeginPlay()
{
	Super::BeginPlay();

	// Niagara System ì„¤ì • ë° í™œì„±í™”
	if (NiagaraSystem)
	{
		NiagaraComponent->SetAsset(NiagaraSystem);
		NiagaraComponent->Activate();
	}

	// ì¼ì • ì‹œê°„ì´ ì§€ë‚œ í›„ ì½œë¦¬ì „ í™œì„±í™”
	GetWorldTimerManager().SetTimer(CollisionTimerHandle, this, &ASOS_NiagaraActor::EnableCollision, CollisionActivationDelay, false);
}

// ì¼ì • ì‹œê°„ í›„ ì½œë¦¬ì „ í™œì„±í™”
void ASOS_NiagaraActor::EnableCollision()
{
	if (BoxCollision)
	{
		BoxCollision->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
		//UE_LOG(LogTemp, Warning, TEXT("ASOS_NiagaraActor: Collision Enabled!"));
	}
}

// Called every frame
void ASOS_NiagaraActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

// Box Collision Overlap ì´ë²¤íŠ¸ ì²˜ë¦¬
void ASOS_NiagaraActor::OnBoxComponentBeginOverlap(
	UPrimitiveComponent* OverlappedComponent,
	AActor* OtherActor,
	UPrimitiveComponent* OtherComp,
	int32 OtherBodyIndex,
	bool bFromSweep,
	const FHitResult& SweepResult)
{
	// ìœ íš¨í•œ ì•¡í„°ì¸ì§€ í™•ì¸ & ìê¸° ìì‹ ê³¼ ë™ì¼í•œ í´ë˜ìŠ¤ì¸ì§€ í™•ì¸ (ê°™ì€ ë‚˜ì´ì•„ê°€ë¼ ì•¡í„°ë¼ë¦¬ ì¶©ëŒ ë°©ì§€)
	if (OtherActor && OtherActor != this && !OtherActor->IsA(ASOS_NiagaraActor::StaticClass()))
	{
		// Apply Damage ì‹¤í–‰
		UGameplayStatics::ApplyDamage(
			OtherActor,
			DamageValue,
			GetInstigatorController(),
			this,
			UDamageType::StaticClass()
		);

		// ìºë¦­í„° ë˜ëŠ” ì ì—ê²Œ í”¼ê²©ëœ ê²½ìš° ì½œë¦¬ì „ ë¹„í™œì„±í™”
		BoxCollision->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	}
	else
	{
		//UE_LOG(LogTemp, Warning, TEXT("ASOS_NiagaraActor: Ignored collision with another NiagaraActor."));
	}

	// ğŸ”¹ ëœë¤ ì‚¬ìš´ë“œ ì¬ìƒ
	if (ImpactSounds.Num() > 0)  // ë°°ì—´ì´ ë¹„ì–´ìˆì§€ ì•Šì€ì§€ í™•ì¸
	{
		int32 RandomIndex = FMath::RandRange(0, ImpactSounds.Num() - 1); // ëœë¤ ì¸ë±ìŠ¤ ì„ íƒ
		USoundBase* RandomSound = ImpactSounds[RandomIndex];

		if (RandomSound)
		{
			UGameplayStatics::PlaySoundAtLocation(this, RandomSound, GetOwner()->GetActorLocation());
			UE_LOG(LogTemp, Warning, TEXT("Impact sound played: %s"), *RandomSound->GetName());
		}
	}
	
}

// Niagara System ì¢…ë£Œ ì‹œ í˜¸ì¶œ
void ASOS_NiagaraActor::OnNiagaraSystemFinished(UNiagaraComponent* PSystem)
{
	Destroy(); // Actor ì‚­ì œ
}
